### ISSUE TITLE
Measured flow rate with IPA half of the set flow

### ISSUE THREAD

**Issue by martijnschouten** [Sensirion/python-uart-scc1#10]
Hi, 

We are using this library to read out an  SLF3S-1300F evaluation kit. To validate that the flowsensor is working correctly we calibrated it using a syringe pump with a syringe filled with IPA. When we use the viewer software we measure the same flow rate as that we set the syringe pump to. However, when we use this library we get only half the flow rate. We did set the sensor to IPA using `sensor = Scc1Slf3x(device, SlfMode.LIQUI_2)`

Could it be that somewhere in the library the data conversion goes wrong, causing the flow rate to be halved?

**Comment by psachs** [comment]
yes this seems an issue with this library. When updating the measurement command the flow unit and scale needs to be read out and updated, else the wrong scale might be applied.
In the example this is done, so it should work correctly
`flow_scale, unit = sensor.get_flow_unit_and_scale()`

Do you use the flow scale that is read after the liquid mode is set?

**Comment by martijnschouten** [comment]
Ah no sorry I did not use the flow_scale. After dividing by flow_scale it gives the correct flow. Thank you very much, this solved the issue.
