### ISSUE TITLE
error code 32: Unknown error when stop_continuous_measurement() not called

### ISSUE THREAD

**Issue by martijnschouten** [Sensirion/python-uart-scc1#9]
I have the SLF3S-1300F Evaluation Kit from Mouser. Usually running the example "contscc1_slf3x_example.py" works nicely. However, if  my program crashes and sensor.stop_continuous_measurement() is not called, then the next times I start the example I cannot connect to the sensor anymore. In this case I get a  `SHDLC device returned error code 32: Unknown error.` from  `device.set_sensor_type(Scc1Slf3x.SENSOR_TYPE)`

The solution seems to be easy: execute an `device.device_reset()` before `device.set_sensor_type(Scc1Slf3x.SENSOR_TYPE)`. For robustness, it might be good to add this to the example.

**Comment by psachs** [comment]
Hi,

yes this is correct. If the measurement is running the sensor type and other configurations can't be changed. In case your script crashes and the sensor does not go through a power cycle it is safe to either run `stop_continuous_measurement` or `device_reset` to ensure we start in a well known state.
